CREATE TABLE [dbo].[Image]
(
	[ImageId] BIGINT NOT NULL  IDENTITY, 
    [URL] NVARCHAR(512) NULL,
	CONSTRAINT [PK_Image] PRIMARY KEY CLUSTERED ([ImageId] ASC)
)

GO

CREATE UNIQUE INDEX [IX_Image_Column] ON [dbo].[Image] ([URL])
